"""sales: add created_at col

Revision ID: 5abb9c57247d
Revises: e29df143e45d
Create Date: 2025-12-03 18:40:08.628564

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '5abb9c57247d'
down_revision: Union[str, None] = 'e29df143e45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'created_at')
    # ### end Alembic commands ###
