"""restock: adding total_quantity

Revision ID: e29df143e45d
Revises: 7133b30ef069
Create Date: 2025-12-03 14:16:25.875274

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e29df143e45d'
down_revision: Union[str, None] = '7133b30ef069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restock_inference', sa.Column('total_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restock_inference', 'total_quantity')
    # ### end Alembic commands ###
